### ISSUE TITLE
Broken linkage for "Evil Genius 2: World Domination"

### ISSUE THREAD

**Issue by arkhovansky** [IsThereAnyDeal/IsThereAnyDeal-Issues#2209]
**1. MERGE ENTRIES**
"Evil Genius 2: World Domination" has two entries on ITAD:
https://isthereanydeal.com/game/evilgeniusiiworlddomination/
https://isthereanydeal.com/game/evilgeniusii/

**2.**
The former links to stores except Steam, the latter links to Steam.

Augmented Steam links to the former.

Note how ITAD <-> Steam links do not correspond.

**Comment by MarkitkaM** [comment]
**ad2)** already fixed

**Comment by arkhovansky** [comment]
Not sure what you mean, is it that point 2 above is fixed?

I'll elaborate on point 2.

https://isthereanydeal.com/game/evilgeniusii/ links to https://store.steampowered.com/app/700600/Evil_Genius_2_World_Domination/.
With Augmented Steam that Steam page links to https://isthereanydeal.com/game/evilgeniusiiworlddomination/ (which does not have Steam store link).

This is not fixed currently.

**Comment by MarkitkaM** [comment]
It is not yet fixed. This bug is moved to the  common issue where similar case will be fixed at once ->

Entries to merge #2324
