### ISSUE TITLE
Oneshot deal

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#706]
OneShot shows up in the deals list as $2.25 on itch.io.  However, clicking on the link and going to the itch.io site give this page (https://grower-yt.itch.io/oneshot) which shows that it's a broken link.  Searching on itch.io gives no indication that OneShot is available on that website.

[Issue created by [deleted]: 2017-04-30]

**Comment by MarkitkaM** [comment]
Now itch.io leads to https://futurecat.itch.io/oneshot.
This is very old bug.
Fixed.

**Comment by Left-Empty** [comment]
Issue is back, now pointing erronously to https://creper159.itch.io/one-shot instead of https://futurecat.itch.io/oneshot , with that version's pricing hijacking the itad entry.
